/*
part 1 basic array kya hai aur memory kaise kaam karti hain?
Array ek continous memory block hota hai jahan hum ek se zyada values ko ek hi variable mein store karte hain har value ko ek index milta hai jo 0 zero se shuru hota hain.
*/

let arr = [10, 20, 30, 40, 50];
//Index:    0,  1,  2,  3,  4

/*
-Element Access: arr[0]-> 10, arr[4]->50
-Length: Array mein kitne elements hain, ye arr.length se  pata chalta hain (yahan 5).
-Last Element index: Always arr.length -1(yahan 5-1=4)
*/
