// let arr = [2,0,4,0,5]
// let result = [];
// for(let i=0; i<arr.length; i++){
//     if(arr[i]!==0){
//         result[i]=arr[i]
//     }
//     console.log(result);
// }




// let arr = [ 50, 40, 30, 20, 10 ];
// let right = 0;
// let left = arr.length - 1;
// while (right < left) {
//   let temp = arr[right];
//   arr[right] = arr[left];
//   arr[left] = temp;
// //   left++;
// //   right--;
//     right++;
//     left--
// }
// console.log(arr);




// let numbers = [12, 35, 1, 10, 34, 1];
// let largest = -Infinity;
// let secondlargest = -Infinity;
// for (let i = 0; i < numbers.length; i++) {
//     let current = numbers[i];
//     if (current > largest) {
//         secondlargest = largest;
//         largest = current;
//     } else if (current > secondlargest && current !== largest) {
//         secondlargest = current;
//     }
// }
// console.log("Largest:", largest);            
// console.log("Second Largest:", secondlargest);